---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 02bd778d4f4ff959546967a3bcaffc6e
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- spec/
